# Jekyll configuration
url: https://bagusaji.com
title: Bagus Aji Santoso
description: Software engineer specializing in interactive 3D web experiences. I build product configurators and web applications with React, Next.js, and Three.js.
author:
  name: Bagus Aji Santoso
  email: bagus@bagusaji.com
  twitter: bgusji
  github: lobothijau
  linkedin: baguzzzaji
include:
  - _redirects

exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

# Page configuration
permalink: /:title/
collections:
  pages:
    output: true
    permalink: /:path/
  portfolios:
    output: true
    permalink: /portfolios/:title/
  books:
    output: true
    permalink: /books/:path/
defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: book
      back: /books
  - scope:
      path: _posts/
      type: posts
    values:
      layout: post
      back: /id/articles
      permalink: /id/articles/:title/
      lang: id
      preview_links_template_id: 999

# Plugin configuration
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-inline-svg
postcss:
  cache: false

# Custom configuration
preview_links:
  site_id: 755
