- title: Zero to Production
  best_if: you need a brand new app and want me to do everything.
  you_get: a developer (me) to build your app and release it to public.
  cta: Chat with Bagus to get started
  description: |
    I write your mobile app with the techology of choice. The app will be 
    integrated with your already built backend APIs or we can also build 
    the web from scratch.
  href: https://wa.me/6281214632571

- title: Maintenance and support
  best_if: you need a maintenance and support for your app.
  you_get: a developer (me) to maintain and support your app.
  cta: Chat with Bagus to get started
  description: |
    I will maintain and support your app. I will also help you to fix bugs 
    and adding new features or improvements.
  href: https://wa.me/6281214632571

- title: Private training / workshop
  best_if: you want to learn mobile application development
  you_get: a custom workshop tailored to your unique needs
  cta: Plan a training with Bagus
  description: |
    Workshops can be arranged as virtual or in-person trianing. It can be a 
    half-day sessions of multi-day events. We will plan the syllabus for 
    the sessions together. 
  href: https://wa.me/6281214632571
